name: GPU tests + code coverage

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main


jobs:
  test_coverage:
    runs-on: ParallelHoss

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - uses: actions/setup-python@v4
        with:
          python-version: 3.11.5
          cache: 'pip'

      - name: Install UV
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh

      - name: Install dependencies
        run: |
          uv venv venv
          source venv/bin/activate
          uv pip install -e .[test]
          uv pip install -r requirements-dev.txt

      - name: Run tests
        run: |
          source venv/bin/activate
          coverage run --source=genlm/backend -m pytest --benchmark-disable
          coverage json --omit "*/test*"
          coverage report --omit "*/test*"

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          fail_ci_if_error: false
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage.json
          slug: genlm/genlm-backend
